<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Laravel\Scout\Searchable;
use OwenIt\Auditing\Contracts\Auditable;

class Book extends Model implements Auditable
{
    use HasFactory;
    use Searchable;
    use \OwenIt\Auditing\Auditable;

    /**
     * Perform any actions required after the model boots.
     * Always eager-load review aggregates for Lab 7 performance compliance.
     */
    protected static function booted()
    {
        static::addGlobalScope('reviews_aggregates', function ($builder) {
            $builder->withAvg('reviews', 'rating')->withCount('reviews');
        });
    }

    /**
     * Get the indexable data array for the model.
     *
     * @return array<string, mixed>
     */
    public function toSearchableArray(): array
    {
        return [
            'id' => (int) $this->id,
            'title' => $this->title,
            'author' => $this->author,
            'isbn' => $this->isbn,
            'publisher' => $this->publisher,
            'description' => $this->description,
            'category' => $this->category?->name,
            'format' => $this->format,
            'published_year' => (int) ($this->published_at?->year ?? 0),
        ];
    }

    /**
     * Determine if the model should be searchable.
     */
    public function shouldBeSearchable(): bool
    {
        return $this->is_active;
    }

    protected $fillable = [
        'category_id',
        'title',
        'author',
        'isbn',
        'price',
        'stock_quantity',
        'description',
        'cover_image',
        'publisher',
        'format',
        'is_active',
        'published_at',
        'pages',
        'language',
        'dimensions',
        'weight',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function reviews()
    {
        return $this->hasMany(Review::class);
    }

    public function orderItems()
    {
        return $this->hasMany(OrderItem::class);
    }

    // Accessor for average rating - optimized for N+1 prevention
    public function getAverageRatingAttribute() {
        // Check all possible attribute names generated by withAvg()
        $avg = $this->attributes['reviews_avg_rating'] 
            ?? $this->attributes['reviews_rating_avg'] 
            ?? null;

        if ($avg !== null) {
            return (float) $avg;
        }
        
        // If reviews relationship is already loaded, use that collection
        if ($this->relationLoaded('reviews')) {
            return (float) ($this->reviews->avg('rating') ?? 0);
        }

        return 0.0;
    }

    // Accessor for reviews count - optimized for N+1 prevention
    public function getReviewsCountAttribute() {
        // Check all possible attribute names generated by withCount()
        $count = $this->attributes['reviews_count'] 
            ?? $this->attributes['reviews_count_count'] 
            ?? null;

        if ($count !== null) {
            return (int) $count;
        }

        if ($this->relationLoaded('reviews')) {
            return $this->reviews->count();
        }

        return 0;
    }

    // ─── Audit Configuration ────────────────────────────────────────

    /**
     * Audit configurations for Book model.
     */
    public function getAuditInclude(): array
    {
        return [
            'category_id',
            'title',
            'author',
            'isbn',
            'price',
            'stock_quantity',
            'description',
        ];
    }

    /**
     * Attributes to exclude from audit.
     */
    public function getAuditExclude(): array
    {
        return [
            'cover_image',
        ];
    }

    /**
     * Custom audit events for Book model.
     */
    public function getAuditEvents(): array
    {
        return [
            'created',
            'updated',
            'deleted',
            'restored',
        ];
    }

    /**
     * Apply filters to book queries
     */
    public function scopeApplyFilters(Builder $query, Request $request): void
    {
        // Category filter
        if ($request->filled('category_id')) {
            $query->where('category_id', $request->input('category_id'));
        }

        // Price range filter
        if ($request->filled('min_price')) {
            $query->where('price', '>=', $request->input('min_price'));
        }
        if ($request->filled('max_price')) {
            $query->where('price', '<=', $request->input('max_price'));
        }

        // Stock filter
        if ($request->filled('in_stock')) {
            $query->where('stock_quantity', '>', 0);
        }

        // Format filter
        if ($request->filled('format')) {
            $query->where('format', $request->input('format'));
        }

        // Author filter
        if ($request->filled('author')) {
            $query->where('author', 'like', '%' . $request->input('author') . '%');
        }

        // Publisher filter
        if ($request->filled('publisher')) {
            $query->where('publisher', $request->input('publisher'));
        }

        // Publication date range
        if ($request->filled('published_after')) {
            $query->where('published_at', '>=', $request->input('published_after'));
        }
        if ($request->filled('published_before')) {
            $query->where('published_at', '<=', $request->input('published_before'));
        }
    }
}
